language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
script:
- yarn ng lint
- yarn test:headless
- yarn ng build --prod --base-href https://Isenr.github.io/travis-demo/
